# Set prefix to Ctrl-Space
unbind C-b
set -g prefix C-a
# bind Space send-prefix

set -g default-terminal "screen-256color"
set -g default-command "reattach-to-user-namespace -l zsh"

set -g status on
set -g status-interval 2
set -g status-bg black
set -g status-fg white

bind y run-shell "reattach-to-user-namespace -l zsh -c 'tmux show-buffer | pbcopy'"

set -s escape-time 30

set -g mouse on

bind c new-window -c "#{pane_current_path}"
bind-key d split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"

setw -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n m-j resize-pane -D 5
bind -n m-k resize-pane -U 5
bind -n m-h resize-pane -L 5
bind -n m-l resize-pane -R 5

bind P paste-buffer
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection
bind-key -t vi-copy 'r' rectangle-toggle

set-option -g status-justify left

set-option -g status-left  '#[fg=cyan][#S#[fg=black,bold]#P#[default]#[fg=cyan]]#[default] '
set-option -g status-right "#[fg=red]#(battery Discharging)#[fg=blue]#(battery Charging) #[default]#[fg=$TMUX_SHELL_COLOR]#h#[default] #{?client_prefix,#[fg=red],#[fg=cyan]}%d %b %R"
set-window-option -g window-status-current-format "[#[fg=white]#I:#W#F#[fg=red]]"

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\ select-pane -l
